### PR TITLE
Fix iframe loading on Firefox

### LINKED ISSUE #45: Plugin doesn't load in Remix/Wizard on Firefox
On Remix in Firefox, the Defender Deploy plugin doesn't load. I get this error:

Image

I'm using ff v136 on a mac

### PR DESCRIPTION
**Pull request by ericglau**
Fixes #45 

This plugin is intended to be embedded in an iframe and uses the parent's URL to determine if it should load the Remix or Wizard version.

It used `document.location.ancestorOrigins` which is available on most browsers except Firefox.  

As a solution, when this is not available, we can use `document.referrer` if the parent iframe allows cross-origin referrer to be passed through (this is allowed in Wizard, but not Remix since it has `<iframe sandbox="... allow-same-origin">`

This PR causes `document.referrer` to be used as a fallback to get the parent URL, and infers Remix if it is still unknown due to the above reasons (which only occurs on Remix+Firefox)

### CODE REVIEW

File: src/routes/+page.svelte [hunk 1]
```diff
@@ -15,18 +15,22 @@
 			return;
 		}
 
-		const ancestorOrigin = document.location.ancestorOrigins[0];
+		const referrer = document.referrer; // Available through Wizard. Empty string through Remix.
+		const ancestorOrigins = document.location.ancestorOrigins; // Not available on Firefox
+
+		const parentUrl = ancestorOrigins !== undefined ? ancestorOrigins[0] : referrer;
```
Comment (CoveMB) [inline src/routes/+page.svelte:21]: nits: could maybe be `ancestorOrigins?.[0] || referrer`

**Review by CoveMB — APPROVED** [review]
